const abby = document.querySelector('#abbyPic')
const american = document.querySelector('#americanPic')
const crested = document.querySelector('#crestedPic')
const himalayan = document.querySelector('#himalayanPic')
const merino = document.querySelector('#merinoPic')
const peruvian = document.querySelector('#peruvianPic')
const rex = document.querySelector('#rexPic')
const sheba = document.querySelector('#shebaPic')
const silkie = document.querySelector('#silkiePic')
const skinny = document.querySelector('#skinnyPic')
const teddy = document.querySelector('#teddyPic')
const texel = document.querySelector('#texelPic')

const abbyText = document.querySelector('#abbyText')
const americanText = document.querySelector('#americanText')
const crestedText = document.querySelector('#crestedText')
const himalayanText = document.querySelector('#himalayanText')
const merinoText = document.querySelector('#merinoText')
const peruvianText = document.querySelector('#peruvianText')
const rexText = document.querySelector('#rexText')
const shebaText = document.querySelector('#shebaText')
const silkieText = document.querySelector('#silkieText')
const skinnyText = document.querySelector('#skinnyText')
const teddyText = document.querySelector('#teddyText')
const texelText = document.querySelector('#texelText')


function show1() {
    abbyText.classList.toggle('hidden')
    americanText.classList.add('hidden')
    crestedText.classList.add('hidden')
    himalayanText.classList.add('hidden')
    merinoText.classList.add('hidden')
    peruvianText.classList.add('hidden')
    rexText.classList.add('hidden')
    shebaText.classList.add('hidden')
    silkieText.classList.add('hidden')
    skinnyText.classList.add('hidden')
    teddyText.classList.add('hidden')
    texelText.classList.add('hidden')

    abby.classList.toggle('hidden')
    american.classList.add('hidden')
    crested.classList.add('hidden')
    himalayan.classList.add('hidden')
    merino.classList.add('hidden')
    peruvian.classList.add('hidden')
    rex.classList.add('hidden')
    sheba.classList.add('hidden')
    silkie.classList.add('hidden')
    skinny.classList.add('hidden')
    teddy.classList.add('hidden')
    texel.classList.add('hidden')
}

function show2() {
    abbyText.classList.add('hidden')
    americanText.classList.toggle('hidden')
    crestedText.classList.add('hidden')
    himalayanText.classList.add('hidden')
    merinoText.classList.add('hidden')
    peruvianText.classList.add('hidden')
    rexText.classList.add('hidden')
    shebaText.classList.add('hidden')
    silkieText.classList.add('hidden')
    skinnyText.classList.add('hidden')
    teddyText.classList.add('hidden')
    texelText.classList.add('hidden')

    abby.classList.add('hidden')
    american.classList.toggle('hidden')
    crested.classList.add('hidden')
    himalayan.classList.add('hidden')
    merino.classList.add('hidden')
    peruvian.classList.add('hidden')
    rex.classList.add('hidden')
    sheba.classList.add('hidden')
    silkie.classList.add('hidden')
    skinny.classList.add('hidden')
    teddy.classList.add('hidden')
    texel.classList.add('hidden')
}

function show3() {
    abbyText.classList.add('hidden')
    americanText.classList.add('hidden')
    crestedText.classList.toggle('hidden')
    himalayanText.classList.add('hidden')
    merinoText.classList.add('hidden')
    peruvianText.classList.add('hidden')
    rexText.classList.add('hidden')
    shebaText.classList.add('hidden')
    silkieText.classList.add('hidden')
    skinnyText.classList.add('hidden')
    teddyText.classList.add('hidden')
    texelText.classList.add('hidden')

    abby.classList.add('hidden')
    american.classList.add('hidden')
    crested.classList.toggle('hidden')
    himalayan.classList.add('hidden')
    merino.classList.add('hidden')
    peruvian.classList.add('hidden')
    rex.classList.add('hidden')
    sheba.classList.add('hidden')
    silkie.classList.add('hidden')
    skinny.classList.add('hidden')
    teddy.classList.add('hidden')
    texel.classList.add('hidden')
}

function show4() {
    abbyText.classList.add('hidden')
    americanText.classList.add('hidden')
    crestedText.classList.add('hidden')
    himalayanText.classList.toggle('hidden')
    merinoText.classList.add('hidden')
    peruvianText.classList.add('hidden')
    rexText.classList.add('hidden')
    shebaText.classList.add('hidden')
    silkieText.classList.add('hidden')
    skinnyText.classList.add('hidden')
    teddyText.classList.add('hidden')
    texelText.classList.add('hidden')

    abby.classList.add('hidden')
    american.classList.add('hidden')
    crested.classList.add('hidden')
    himalayan.classList.toggle('hidden')
    merino.classList.add('hidden')
    peruvian.classList.add('hidden')
    rex.classList.add('hidden')
    sheba.classList.add('hidden')
    silkie.classList.add('hidden')
    skinny.classList.add('hidden')
    teddy.classList.add('hidden')
    texel.classList.add('hidden')
}

function show5() {
    abbyText.classList.add('hidden')
    americanText.classList.add('hidden')
    crestedText.classList.add('hidden')
    himalayanText.classList.add('hidden')
    merinoText.classList.toggle('hidden')
    peruvianText.classList.add('hidden')
    rexText.classList.add('hidden')
    shebaText.classList.add('hidden')
    silkieText.classList.add('hidden')
    skinnyText.classList.add('hidden')
    teddyText.classList.add('hidden')
    texelText.classList.add('hidden')

    abby.classList.add('hidden')
    american.classList.add('hidden')
    crested.classList.add('hidden')
    himalayan.classList.add('hidden')
    merino.classList.toggle('hidden')
    peruvian.classList.add('hidden')
    rex.classList.add('hidden')
    sheba.classList.add('hidden')
    silkie.classList.add('hidden')
    skinny.classList.add('hidden')
    teddy.classList.add('hidden')
    texel.classList.add('hidden')
}

function show6() {
    abbyText.classList.add('hidden')
    americanText.classList.add('hidden')
    crestedText.classList.add('hidden')
    himalayanText.classList.add('hidden')
    merinoText.classList.add('hidden')
    peruvianText.classList.toggle('hidden')
    rexText.classList.add('hidden')
    shebaText.classList.add('hidden')
    silkieText.classList.add('hidden')
    skinnyText.classList.add('hidden')
    teddyText.classList.add('hidden')
    texelText.classList.add('hidden')

    abby.classList.add('hidden')
    american.classList.add('hidden')
    crested.classList.add('hidden')
    himalayan.classList.add('hidden')
    merino.classList.add('hidden')
    peruvian.classList.toggle('hidden')
    rex.classList.add('hidden')
    sheba.classList.add('hidden')
    silkie.classList.add('hidden')
    skinny.classList.add('hidden')
    teddy.classList.add('hidden')
    texel.classList.add('hidden')
}

function show7() {
    abbyText.classList.add('hidden')
    americanText.classList.add('hidden')
    crestedText.classList.add('hidden')
    himalayanText.classList.add('hidden')
    merinoText.classList.add('hidden')
    peruvianText.classList.add('hidden')
    rexText.classList.toggle('hidden')
    shebaText.classList.add('hidden')
    silkieText.classList.add('hidden')
    skinnyText.classList.add('hidden')
    teddyText.classList.add('hidden')
    texelText.classList.add('hidden')

    abby.classList.add('hidden')
    american.classList.add('hidden')
    crested.classList.add('hidden')
    himalayan.classList.add('hidden')
    merino.classList.add('hidden')
    peruvian.classList.add('hidden')
    rex.classList.toggle('hidden')
    sheba.classList.add('hidden')
    silkie.classList.add('hidden')
    skinny.classList.add('hidden')
    teddy.classList.add('hidden')
    texel.classList.add('hidden')
}

function show8() {
    abbyText.classList.add('hidden')
    americanText.classList.add('hidden')
    crestedText.classList.add('hidden')
    himalayanText.classList.add('hidden')
    merinoText.classList.add('hidden')
    peruvianText.classList.add('hidden')
    rexText.classList.add('hidden')
    shebaText.classList.toggle('hidden')
    silkieText.classList.add('hidden')
    skinnyText.classList.add('hidden')
    teddyText.classList.add('hidden')
    texelText.classList.add('hidden')

    abby.classList.add('hidden')
    american.classList.add('hidden')
    crested.classList.add('hidden')
    himalayan.classList.add('hidden')
    merino.classList.add('hidden')
    peruvian.classList.add('hidden')
    rex.classList.add('hidden')
    sheba.classList.toggle('hidden')
    silkie.classList.add('hidden')
    skinny.classList.add('hidden')
    teddy.classList.add('hidden')
    texel.classList.add('hidden')
}

function show9() {
    abbyText.classList.add('hidden')
    americanText.classList.add('hidden')
    crestedText.classList.add('hidden')
    himalayanText.classList.add('hidden')
    merinoText.classList.add('hidden')
    peruvianText.classList.add('hidden')
    rexText.classList.add('hidden')
    shebaText.classList.add('hidden')
    silkieText.classList.toggle('hidden')
    skinnyText.classList.add('hidden')
    teddyText.classList.add('hidden')
    texelText.classList.add('hidden')

    abby.classList.add('hidden')
    american.classList.add('hidden')
    crested.classList.add('hidden')
    himalayan.classList.add('hidden')
    merino.classList.add('hidden')
    peruvian.classList.add('hidden')
    rex.classList.add('hidden')
    sheba.classList.add('hidden')
    silkie.classList.toggle('hidden')
    skinny.classList.add('hidden')
    teddy.classList.add('hidden')
    texel.classList.add('hidden')
}

function show10() {
    abbyText.classList.add('hidden')
    americanText.classList.add('hidden')
    crestedText.classList.add('hidden')
    himalayanText.classList.add('hidden')
    merinoText.classList.add('hidden')
    peruvianText.classList.add('hidden')
    rexText.classList.add('hidden')
    shebaText.classList.add('hidden')
    silkieText.classList.add('hidden')
    skinnyText.classList.toggle('hidden')
    teddyText.classList.add('hidden')
    texelText.classList.add('hidden')

    abby.classList.add('hidden')
    american.classList.add('hidden')
    crested.classList.add('hidden')
    himalayan.classList.add('hidden')
    merino.classList.add('hidden')
    peruvian.classList.add('hidden')
    rex.classList.add('hidden')
    sheba.classList.add('hidden')
    silkie.classList.add('hidden')
    skinny.classList.toggle('hidden')
    teddy.classList.add('hidden')
    texel.classList.add('hidden')
}

function show11() {
    abbyText.classList.add('hidden')
    americanText.classList.add('hidden')
    crestedText.classList.add('hidden')
    himalayanText.classList.add('hidden')
    merinoText.classList.add('hidden')
    peruvianText.classList.add('hidden')
    rexText.classList.add('hidden')
    shebaText.classList.add('hidden')
    silkieText.classList.add('hidden')
    skinnyText.classList.add('hidden')
    teddyText.classList.toggle('hidden')
    texelText.classList.add('hidden')

    abby.classList.add('hidden')
    american.classList.add('hidden')
    crested.classList.add('hidden')
    himalayan.classList.add('hidden')
    merino.classList.add('hidden')
    peruvian.classList.add('hidden')
    rex.classList.add('hidden')
    sheba.classList.add('hidden')
    silkie.classList.add('hidden')
    skinny.classList.add('hidden')
    teddy.classList.toggle('hidden')
    texel.classList.add('hidden')
}

function show12() {
    abbyText.classList.add('hidden')
    americanText.classList.add('hidden')
    crestedText.classList.add('hidden')
    himalayanText.classList.add('hidden')
    merinoText.classList.add('hidden')
    peruvianText.classList.add('hidden')
    rexText.classList.add('hidden')
    shebaText.classList.add('hidden')
    silkieText.classList.add('hidden')
    skinnyText.classList.add('hidden')
    teddyText.classList.add('hidden')
    texelText.classList.toggle('hidden')

    abby.classList.add('hidden')
    american.classList.add('hidden')
    crested.classList.add('hidden')
    himalayan.classList.add('hidden')
    merino.classList.add('hidden')
    peruvian.classList.add('hidden')
    rex.classList.add('hidden')
    sheba.classList.add('hidden')
    silkie.classList.add('hidden')
    skinny.classList.add('hidden')
    teddy.classList.add('hidden')
    texel.classList.toggle('hidden')
}


